baseURL = "/"
languageCode = "pt-BR"
title = "Jan Limpens"
subtitle = "ilustrador"
theme = "basedoff"
enableInlineShortcodes = true
defaultContentLanguage = "pt-BR"

[params]
description = "Ilustrações"
mainSections = ['posts']
copyright = "© Jan Limpens"
customCss = ["lightbox2/css/lightbox.min.css", "https://cdn.typenugget.com/tPS0VEQ05A?nug=UlVR0tAVFl", "css/custom.css"]
customJs = ["js/jquery.js", "lightbox2/js/lightbox.min.js"]
defaultImageFit = "800x800"
defaultThumbCrop = "150x150 smart"

[permalinks]
blog  = "/blog/:year/:month/:title/"
[[menu.main]]
weight = 2
name = "ilustrações"
url = "/portfolio/ilustracoes/"
[[menu.main]]
weight = 3
name = "livros"
url = "/portfolio/livros/"
[[menu.main]]
weight = 4
name = "quadrinhos"
url = "/portfolio/hqs/"
[[menu.main]]
weight = 5
name = "sobre"
url = "/sobre/"
[[menu.main]]
weight = 6
name = "contato"
url = "/contato/"

[markup]
  [markup.goldmark.renderer]
    unsafe=true
