baseURL = "/"
languageCode = "pt-br"
title = "Jan Limpens"
subtitle = "ilustrador"
theme = "ezhil"
enableInlineShortcodes = true
defaultContentLanguage = "pt-br"

[params]
description = "Ilustrações"
mainSections = ['posts']
copyright = "© Jan Limpens"
customCss = ["styles/custom.css", "lightbox2/css/lightbox.min.css"]
customJs = ["js/jquery.js", "lightbox2/js/lightbox.min.js"]
subtitle = "Desenhista"

[permalinks]
blog  = "/blog/:year/:month/:title/"
[[menu.main]]
weight = 1
name = "notícias"
url = "/"
[[menu.main]]
weight = 2
name = "ilustrações"
url = "/portfolio/ilustracoes/"
[[menu.main]]
weight = 3
name = "livros"
url = "/portfolio/livros/"
[[menu.main]]
weight = 4
name = "histórias em quadrinhos"
url = "/portfolio/hqs/"
[[menu.main]]
weight = 5
name = "sobre"
url = "/sobre/"
[[menu.main]]
weight = 6
name = "contato"
url = "/contato/"