---
label: default
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: author
  label: author
- type: datetime
  name: date
  label: date
- type: datetime
  name: publishdate
  label: publishdate
- type: datetime
  name: lastmod
  label: lastmod
- type: text
  name: description
  label: description
- type: list
  name: tags
  label: tags
